package model

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/QuantumNous/new-api/common"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const (
	ChannelGroupMonitorResultSuccess         = "success"
	ChannelGroupMonitorResultUpstreamFailure = "upstream_failure"
	ChannelGroupMonitorResultRateLimited     = "rate_limited"
	ChannelGroupMonitorResultLocalFailure    = "local_failure"
	ChannelGroupMonitorResultUnavailable     = "unavailable"
	ChannelGroupMonitorResultSkipped         = "skipped"

	ChannelGroupMonitorTriggerScheduled = "scheduled"
	ChannelGroupMonitorTriggerManual    = "manual"

	ChannelGroupMonitorDefaultIntervalSeconds = 60
	ChannelGroupMonitorMinIntervalSeconds     = 30
	ChannelGroupMonitorMaxIntervalSeconds     = 86400
	ChannelGroupMonitorDefaultDisplayValue    = 60
	ChannelGroupMonitorDefaultDisplayUnit     = ChannelStatusProbeDisplayUnitMinute
	ChannelGroupMonitorMaxGroups              = 100
	ChannelGroupMonitorLeaseSeconds           = 600
	ChannelMonitorGroupProbeLogKey            = "channel_monitor_group_probe"
)

var (
	ErrChannelGroupMonitorConfigChanged = errors.New("分组监控配置已被其他请求修改，请刷新后重试")
	ErrChannelGroupMonitorManualPending = errors.New("分组监控已有待执行或正在执行的立即检测")
)

// ChannelGroupMonitorGroup is the durable, ordered user-facing group list.
// A concrete probe model is required so a configuration change never silently
// changes the external traffic generated by the worker.
type ChannelGroupMonitorGroup struct {
	GroupName      string `json:"group_name"`
	ProbeModel     string `json:"probe_model"`
	DisplayInitial string `json:"display_initial,omitempty"`
}

type ChannelGroupMonitorConfig struct {
	Id                int64  `json:"id" gorm:"primaryKey"`
	Enabled           bool   `json:"enabled" gorm:"index:idx_channel_group_monitor_due,priority:1"`
	GroupsJSON        string `json:"-" gorm:"type:text;not null"`
	IntervalSeconds   int    `json:"interval_seconds"`
	DisplayValue      int    `json:"display_value"`
	DisplayUnit       string `json:"display_unit" gorm:"type:varchar(16)"`
	Revision          int64  `json:"revision" gorm:"bigint"`
	NextRunAt         int64  `json:"next_run_at" gorm:"bigint;index:idx_channel_group_monitor_due,priority:2"`
	ManualRequestId   string `json:"manual_request_id" gorm:"type:varchar(64);index:idx_channel_group_monitor_manual_due,priority:1"`
	ManualRequestedAt int64  `json:"manual_requested_at" gorm:"bigint;index:idx_channel_group_monitor_manual_due,priority:2,sort:desc"`
	LeaseToken        string `json:"-" gorm:"type:varchar(64)"`
	LeaseUntil        int64  `json:"lease_until" gorm:"bigint;index:idx_channel_group_monitor_due,priority:3;index:idx_channel_group_monitor_manual_due,priority:3"`
	RunningTrigger    string `json:"running_trigger" gorm:"type:varchar(16)"`
	RunningRunId      string `json:"running_run_id" gorm:"type:varchar(64)"`
	RunningStartedAt  int64  `json:"running_started_at" gorm:"bigint"`
	CreatedAt         int64  `json:"created_at" gorm:"bigint"`
	UpdatedAt         int64  `json:"updated_at" gorm:"bigint"`
}

func (config ChannelGroupMonitorConfig) Groups() ([]ChannelGroupMonitorGroup, error) {
	groups := []ChannelGroupMonitorGroup{}
	if strings.TrimSpace(config.GroupsJSON) == "" {
		return groups, nil
	}
	if err := common.UnmarshalJsonStr(config.GroupsJSON, &groups); err != nil {
		return nil, fmt.Errorf("解析分组监控配置失败: %w", err)
	}
	return groups, nil
}

type ChannelGroupMonitorState struct {
	Id                 int64    `json:"id"`
	GroupName          string   `json:"group_name" gorm:"type:varchar(64);not null;uniqueIndex"`
	ExecutionId        int64    `json:"execution_id" gorm:"bigint"`
	RunId              string   `json:"run_id" gorm:"type:varchar(64)"`
	ProbeModel         string   `json:"probe_model" gorm:"type:varchar(255)"`
	Result             string   `json:"result" gorm:"type:varchar(32)"`
	RequestDispatched  bool     `json:"request_dispatched"`
	ResponseTimeMs     *float64 `json:"response_time_ms"`
	FirstTokenMs       *float64 `json:"first_token_ms"`
	TPS                *float64 `json:"tps"`
	FinishedAt         int64    `json:"finished_at" gorm:"bigint;index"`
	LastSuccessAt      int64    `json:"last_success_at" gorm:"bigint"`
	LastFailureAt      int64    `json:"last_failure_at" gorm:"bigint"`
	ConsecutiveSuccess int      `json:"consecutive_success"`
	ConsecutiveFailure int      `json:"consecutive_failure"`
	CreatedAt          int64    `json:"created_at" gorm:"bigint"`
	UpdatedAt          int64    `json:"updated_at" gorm:"bigint"`
}

// ChannelGroupMonitorExecution stores one logical probe. Upstream retries may
// have multiple physical attempts, but only their final result is exposed in
// group health and success-rate calculations.
type ChannelGroupMonitorExecution struct {
	Id                 int64    `json:"id" gorm:"index:idx_channel_group_monitor_execution_group_finished,priority:3,sort:desc"`
	RunId              string   `json:"run_id" gorm:"type:varchar(64);not null;uniqueIndex:idx_channel_group_monitor_execution_run_group"`
	GroupName          string   `json:"group_name" gorm:"type:varchar(64);not null;uniqueIndex:idx_channel_group_monitor_execution_run_group;index:idx_channel_group_monitor_execution_group_finished,priority:1"`
	ConfigRevision     int64    `json:"config_revision" gorm:"bigint"`
	Trigger            string   `json:"trigger" gorm:"type:varchar(16)"`
	ProbeModel         string   `json:"probe_model" gorm:"type:varchar(255)"`
	ChannelId          int      `json:"channel_id" gorm:"index"`
	RequestId          string   `json:"request_id" gorm:"type:varchar(64)"`
	Result             string   `json:"result" gorm:"type:varchar(32);index"`
	RequestDispatched  bool     `json:"request_dispatched"`
	ResponseTimeMs     *float64 `json:"response_time_ms"`
	FirstTokenMs       *float64 `json:"first_token_ms"`
	TPS                *float64 `json:"tps"`
	SettledCostNanoCNY *int64   `json:"settled_cost_nano_cny"`
	ErrorCode          string   `json:"error_code" gorm:"type:varchar(128)"`
	ErrorMessage       string   `json:"error_message" gorm:"type:varchar(512)"`
	StartedAt          int64    `json:"started_at" gorm:"bigint"`
	FinishedAt         int64    `json:"finished_at" gorm:"bigint;index:idx_channel_group_monitor_execution_group_finished,priority:2,sort:desc"`
	CreatedAt          int64    `json:"created_at" gorm:"bigint"`
}

type ChannelGroupMonitorExecutionSummary struct {
	GroupName   string `gorm:"column:group_name"`
	Result      string `gorm:"column:result"`
	ResultCount int64  `gorm:"column:result_count"`
}

type ChannelGroupMonitorConfigInput struct {
	Enabled         bool
	Groups          []ChannelGroupMonitorGroup
	IntervalSeconds int
	DisplayValue    int
	DisplayUnit     string
	Revision        int64
}

type ChannelGroupMonitorClaim struct {
	Config          ChannelGroupMonitorConfig
	Groups          []ChannelGroupMonitorGroup
	Trigger         string
	RunId           string
	ManualRequestId string
	LeaseToken      string
}

func normalizeChannelGroupMonitorDisplay(value int, unit string) (int, string) {
	if IsChannelStatusProbeDisplayAllowed(value, unit) {
		return value, unit
	}
	return ChannelGroupMonitorDefaultDisplayValue, ChannelGroupMonitorDefaultDisplayUnit
}

func nextChannelGroupMonitorRunAt(after int64, intervalSeconds int) int64 {
	interval := int64(intervalSeconds)
	if after < 0 || interval <= 0 {
		return 0
	}
	return after - after%interval + interval
}

func GetChannelGroupMonitorConfig() (ChannelGroupMonitorConfig, error) {
	var config ChannelGroupMonitorConfig
	err := DB.Where("id = ?", 1).First(&config).Error
	return config, err
}

func GetChannelGroupMonitorConfigOrDefault() (ChannelGroupMonitorConfig, error) {
	config, err := GetChannelGroupMonitorConfig()
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return ChannelGroupMonitorConfig{
			Id: 1, IntervalSeconds: ChannelGroupMonitorDefaultIntervalSeconds,
			DisplayValue: ChannelGroupMonitorDefaultDisplayValue,
			DisplayUnit:  ChannelGroupMonitorDefaultDisplayUnit,
		}, nil
	}
	return config, err
}

func SaveChannelGroupMonitorConfig(input ChannelGroupMonitorConfigInput, now int64) (ChannelGroupMonitorConfig, error) {
	groupsJSON, err := common.Marshal(input.Groups)
	if err != nil {
		return ChannelGroupMonitorConfig{}, err
	}
	displayValue, displayUnit := normalizeChannelGroupMonitorDisplay(input.DisplayValue, input.DisplayUnit)
	var saved ChannelGroupMonitorConfig
	err = DB.Transaction(func(tx *gorm.DB) error {
		var current ChannelGroupMonitorConfig
		findErr := lockForUpdate(tx).Where("id = ?", 1).First(&current).Error
		if errors.Is(findErr, gorm.ErrRecordNotFound) {
			if input.Revision != 0 {
				return ErrChannelGroupMonitorConfigChanged
			}
			nextRunAt := int64(0)
			if input.Enabled && len(input.Groups) > 0 {
				nextRunAt = nextChannelGroupMonitorRunAt(now, input.IntervalSeconds)
			}
			saved = ChannelGroupMonitorConfig{
				Id: 1, Enabled: input.Enabled, GroupsJSON: string(groupsJSON),
				IntervalSeconds: input.IntervalSeconds, DisplayValue: displayValue, DisplayUnit: displayUnit,
				NextRunAt: nextRunAt, Revision: 1, CreatedAt: now, UpdatedAt: now,
			}
			return tx.Create(&saved).Error
		}
		if findErr != nil {
			return findErr
		}
		if current.Revision != input.Revision {
			return ErrChannelGroupMonitorConfigChanged
		}
		nextRunAt := current.NextRunAt
		configurationChanged := current.GroupsJSON != string(groupsJSON) || current.IntervalSeconds != input.IntervalSeconds
		if !input.Enabled || len(input.Groups) == 0 {
			nextRunAt = 0
		} else if !current.Enabled || configurationChanged || nextRunAt <= 0 || nextRunAt%int64(input.IntervalSeconds) != 0 {
			nextRunAt = nextChannelGroupMonitorRunAt(now, input.IntervalSeconds)
		}
		updated := tx.Model(&ChannelGroupMonitorConfig{}).
			Where("id = ? AND revision = ?", current.Id, current.Revision).
			Updates(map[string]any{
				"enabled": input.Enabled, "groups_json": string(groupsJSON),
				"interval_seconds": input.IntervalSeconds, "display_value": displayValue,
				"display_unit": displayUnit, "next_run_at": nextRunAt,
				"revision": current.Revision + 1, "updated_at": now,
			})
		if updated.Error != nil {
			return updated.Error
		}
		if updated.RowsAffected != 1 {
			return ErrChannelGroupMonitorConfigChanged
		}
		return tx.Where("id = ?", current.Id).First(&saved).Error
	})
	return saved, err
}

func RequestChannelGroupMonitorManualRun(now int64) (string, error) {
	requestId := common.GetUUID()
	err := DB.Transaction(func(tx *gorm.DB) error {
		var config ChannelGroupMonitorConfig
		if err := lockForUpdate(tx).Where("id = ?", 1).First(&config).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return errors.New("请先保存至少一个监控分组")
			}
			return err
		}
		groups, err := config.Groups()
		if err != nil {
			return err
		}
		if len(groups) == 0 {
			return errors.New("请先保存至少一个监控分组")
		}
		if config.LeaseUntil <= now && strings.TrimSpace(config.RunningRunId) != "" {
			staleManualRun := config.RunningTrigger == ChannelGroupMonitorTriggerManual
			clearUpdates := map[string]any{
				"lease_token": "", "lease_until": int64(0), "running_trigger": "",
				"running_run_id": "", "running_started_at": int64(0), "updated_at": now,
			}
			if staleManualRun {
				clearUpdates["manual_request_id"] = ""
				clearUpdates["manual_requested_at"] = int64(0)
			}
			cleared := tx.Model(&ChannelGroupMonitorConfig{}).
				Where("id = ? AND lease_until <= ?", config.Id, now).
				Updates(clearUpdates)
			if cleared.Error != nil {
				return cleared.Error
			}
			config.RunningRunId = ""
			if staleManualRun {
				config.ManualRequestId = ""
			}
		}
		if strings.TrimSpace(config.ManualRequestId) != "" || strings.TrimSpace(config.RunningRunId) != "" {
			return ErrChannelGroupMonitorManualPending
		}
		updated := tx.Model(&ChannelGroupMonitorConfig{}).
			Where("id = ? AND manual_request_id = ? AND running_run_id = ?", 1, "", "").
			Updates(map[string]any{
				"manual_request_id": requestId, "manual_requested_at": now, "updated_at": now,
			})
		if updated.Error != nil {
			return updated.Error
		}
		if updated.RowsAffected != 1 {
			return ErrChannelGroupMonitorManualPending
		}
		return nil
	})
	return requestId, err
}

func ClaimDueChannelGroupMonitor(now int64) (*ChannelGroupMonitorClaim, error) {
	var candidate ChannelGroupMonitorConfig
	err := DB.Where("id = ? AND lease_until <= ?", 1, now).
		Where("manual_request_id <> ? OR (enabled = ? AND next_run_at > 0 AND next_run_at <= ?)", "", true, now).
		First(&candidate).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	groups, err := candidate.Groups()
	if err != nil {
		return nil, err
	}
	if len(groups) == 0 {
		return nil, nil
	}
	trigger := ChannelGroupMonitorTriggerScheduled
	runId := common.GetUUID()
	manualRequestId := strings.TrimSpace(candidate.ManualRequestId)
	claimQuery := DB.Model(&ChannelGroupMonitorConfig{}).
		Where("id = ? AND revision = ? AND lease_until <= ?", candidate.Id, candidate.Revision, now)
	if manualRequestId != "" {
		trigger = ChannelGroupMonitorTriggerManual
		runId = manualRequestId
		claimQuery = claimQuery.Where("manual_request_id = ?", manualRequestId)
	} else {
		claimQuery = claimQuery.Where("enabled = ? AND next_run_at > 0 AND next_run_at <= ?", true, now)
	}
	leaseToken := common.GetUUID()
	updates := map[string]any{
		"lease_token": leaseToken, "lease_until": now + ChannelGroupMonitorLeaseSeconds,
		"running_trigger": trigger, "running_run_id": runId, "running_started_at": now, "updated_at": now,
	}
	if trigger == ChannelGroupMonitorTriggerScheduled {
		updates["next_run_at"] = nextChannelGroupMonitorRunAt(candidate.NextRunAt, candidate.IntervalSeconds)
	}
	claimed := claimQuery.Updates(updates)
	if claimed.Error != nil {
		return nil, claimed.Error
	}
	if claimed.RowsAffected != 1 {
		return nil, nil
	}
	return &ChannelGroupMonitorClaim{
		Config: candidate, Groups: groups, Trigger: trigger, RunId: runId,
		ManualRequestId: manualRequestId, LeaseToken: leaseToken,
	}, nil
}

func RenewChannelGroupMonitorLease(claim ChannelGroupMonitorClaim, now int64) (bool, error) {
	updated := DB.Model(&ChannelGroupMonitorConfig{}).
		Where("id = ? AND revision = ? AND lease_token = ?", claim.Config.Id, claim.Config.Revision, claim.LeaseToken).
		Updates(map[string]any{"lease_until": now + ChannelGroupMonitorLeaseSeconds, "updated_at": now})
	return updated.RowsAffected == 1, updated.Error
}

func IsChannelGroupMonitorLeaseCurrent(claim ChannelGroupMonitorClaim, now int64) (bool, error) {
	var count int64
	err := DB.Model(&ChannelGroupMonitorConfig{}).
		Where("id = ? AND revision = ? AND lease_token = ? AND lease_until > ?", claim.Config.Id, claim.Config.Revision, claim.LeaseToken, now).
		Count(&count).Error
	return count == 1, err
}

func CompleteChannelGroupMonitorClaim(claim ChannelGroupMonitorClaim, finishedAt int64) error {
	updates := map[string]any{
		"lease_token": "", "lease_until": int64(0), "running_trigger": "", "running_run_id": "",
		"running_started_at": int64(0), "updated_at": finishedAt,
	}
	if claim.Trigger == ChannelGroupMonitorTriggerManual {
		updates["manual_request_id"] = ""
		updates["manual_requested_at"] = int64(0)
	}
	updated := DB.Model(&ChannelGroupMonitorConfig{}).
		Where("id = ? AND revision = ? AND lease_token = ?", claim.Config.Id, claim.Config.Revision, claim.LeaseToken).
		Updates(updates)
	if updated.Error != nil || updated.RowsAffected == 1 {
		return updated.Error
	}
	return DB.Model(&ChannelGroupMonitorConfig{}).
		Where("id = ? AND lease_token = ?", claim.Config.Id, claim.LeaseToken).
		Updates(updates).Error
}

func SaveChannelGroupMonitorExecution(execution *ChannelGroupMonitorExecution) (bool, error) {
	if execution == nil || strings.TrimSpace(execution.RunId) == "" || strings.TrimSpace(execution.GroupName) == "" {
		return false, errors.New("分组监控执行记录无效")
	}
	if execution.CreatedAt <= 0 {
		execution.CreatedAt = execution.FinishedAt
	}
	created := false
	err := DB.Transaction(func(tx *gorm.DB) error {
		inserted := tx.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "run_id"}, {Name: "group_name"}},
			DoNothing: true,
		}).Create(execution)
		if inserted.Error != nil {
			return inserted.Error
		}
		if inserted.RowsAffected == 0 {
			var existing ChannelGroupMonitorExecution
			if err := tx.Where("run_id = ? AND group_name = ?", execution.RunId, execution.GroupName).First(&existing).Error; err != nil {
				return err
			}
			*execution = existing
			return nil
		}
		created = true

		var state ChannelGroupMonitorState
		stateErr := lockForUpdate(tx).Where("group_name = ?", execution.GroupName).First(&state).Error
		if errors.Is(stateErr, gorm.ErrRecordNotFound) {
			state = ChannelGroupMonitorState{GroupName: execution.GroupName, CreatedAt: execution.FinishedAt}
		} else if stateErr != nil {
			return stateErr
		}
		if execution.Result != ChannelGroupMonitorResultSkipped &&
			(execution.FinishedAt > state.FinishedAt || (execution.FinishedAt == state.FinishedAt && execution.Id > state.ExecutionId)) {
			state.ExecutionId = execution.Id
			state.RunId = execution.RunId
			state.ProbeModel = execution.ProbeModel
			state.Result = execution.Result
			state.RequestDispatched = execution.RequestDispatched
			if execution.Result == ChannelGroupMonitorResultSuccess {
				state.ResponseTimeMs = execution.ResponseTimeMs
				state.FirstTokenMs = execution.FirstTokenMs
				state.TPS = execution.TPS
			} else {
				state.ResponseTimeMs = nil
				state.FirstTokenMs = nil
				state.TPS = nil
			}
			state.FinishedAt = execution.FinishedAt
			if execution.Result == ChannelGroupMonitorResultSuccess {
				state.LastSuccessAt = execution.FinishedAt
				state.ConsecutiveSuccess++
				state.ConsecutiveFailure = 0
			} else if execution.Result != ChannelGroupMonitorResultSkipped {
				state.LastFailureAt = execution.FinishedAt
				state.ConsecutiveFailure++
				state.ConsecutiveSuccess = 0
			}
		}
		state.UpdatedAt = max(state.UpdatedAt, execution.FinishedAt)
		if state.Id == 0 {
			return tx.Create(&state).Error
		}
		return tx.Save(&state).Error
	})
	return created, err
}

func GetChannelGroupMonitorStates() ([]ChannelGroupMonitorState, error) {
	var states []ChannelGroupMonitorState
	err := DB.Order("group_name ASC").Find(&states).Error
	return states, err
}

func GetChannelGroupMonitorExecutionsSince(startedAt int64) ([]ChannelGroupMonitorExecution, error) {
	var executions []ChannelGroupMonitorExecution
	err := DB.Where("finished_at >= ? AND result <> ?", startedAt, ChannelGroupMonitorResultSkipped).
		Order("group_name ASC, finished_at DESC, id DESC").Find(&executions).Error
	return executions, err
}

// GetChannelGroupMonitorExecutionWindowSince returns every execution in the
// requested time range, including skipped executions. The public monitor
// window uses skipped results to distinguish an empty time slot from a probe
// that was explicitly skipped, while the success-rate summary above keeps its
// historical non-skipped semantics.
func GetChannelGroupMonitorExecutionWindowSince(startedAt int64) ([]ChannelGroupMonitorExecution, error) {
	var executions []ChannelGroupMonitorExecution
	err := DB.Select("group_name, result, response_time_ms, first_token_ms, tps, finished_at").
		Where("finished_at >= ?", startedAt).
		Order("group_name ASC, finished_at ASC, id ASC").Find(&executions).Error
	return executions, err
}

func GetChannelGroupMonitorExecutionSummariesSince(startedAt int64) ([]ChannelGroupMonitorExecutionSummary, error) {
	var summaries []ChannelGroupMonitorExecutionSummary
	err := DB.Model(&ChannelGroupMonitorExecution{}).
		Select("group_name, result, COUNT(*) AS result_count").
		Where("finished_at >= ? AND result <> ?", startedAt, ChannelGroupMonitorResultSkipped).
		Group("group_name, result").
		Find(&summaries).Error
	return summaries, err
}

func ListChannelGroupMonitorExecutions(page int, pageSize int, groupName string, result string) ([]ChannelGroupMonitorExecution, int64, error) {
	query := DB.Model(&ChannelGroupMonitorExecution{})
	if strings.TrimSpace(groupName) != "" {
		query = query.Where("group_name = ?", strings.TrimSpace(groupName))
	}
	if strings.TrimSpace(result) != "" {
		query = query.Where("result = ?", strings.TrimSpace(result))
	}
	var total int64
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}
	var executions []ChannelGroupMonitorExecution
	err := query.Order("finished_at DESC, id DESC").Offset((page - 1) * pageSize).Limit(pageSize).Find(&executions).Error
	return executions, total, err
}

func DeleteChannelGroupMonitorExecutionsBefore(
	ctx context.Context,
	cutoff int64,
	batchSize int,
	budget ChannelMonitorCleanupBudget,
) (int64, error) {
	if cutoff <= 0 || batchSize <= 0 {
		return 0, errors.New("分组监控历史清理参数无效")
	}
	if !DB.Migrator().HasTable(&ChannelGroupMonitorExecution{}) {
		return 0, nil
	}
	var deletedRows int64
	db := DB.WithContext(ctx)
	for {
		if budget.Exhausted() {
			return deletedRows, nil
		}
		var ids []int64
		if err := db.Model(&ChannelGroupMonitorExecution{}).
			Where("finished_at < ?", cutoff).
			Order("finished_at ASC, id ASC").
			Limit(batchSize).
			Pluck("id", &ids).Error; err != nil {
			return deletedRows, err
		}
		if len(ids) == 0 {
			return deletedRows, nil
		}
		deleted := db.Where("id IN ?", ids).Delete(&ChannelGroupMonitorExecution{})
		if deleted.Error != nil {
			return deletedRows, deleted.Error
		}
		deletedRows += deleted.RowsAffected
	}
}

func ChannelGroupMonitorGroupsByName(groups []ChannelGroupMonitorGroup) map[string]ChannelGroupMonitorGroup {
	byName := make(map[string]ChannelGroupMonitorGroup, len(groups))
	for _, group := range groups {
		byName[group.GroupName] = group
	}
	return byName
}

func SortChannelGroupMonitorGroups(groups []ChannelGroupMonitorGroup) {
	sort.Slice(groups, func(i int, j int) bool {
		return groups[i].GroupName < groups[j].GroupName
	})
}
