package service

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/model"
	"github.com/go-redis/redis/v8"
)

const (
	ChannelDailyCostRedisStream        = "channel_cost:v1:events"
	ChannelDailyCostRedisConsumerGroup = "channel-cost-ledger-v1"
	ChannelDailyCostRedisDeadLetter    = "channel_cost:v1:dead"

	channelDailyCostRedisFieldEventID = "event_id"
	channelDailyCostRedisFieldPayload = "payload"

	channelDailyCostOutboxBatchSize          = 256
	channelDailyCostOutboxPublishTimeout     = 250 * time.Millisecond
	channelDailyCostOutboxDBFallbackTimeout  = 750 * time.Millisecond
	channelDailyCostOutboxDBOperationTimeout = 3 * time.Second
	channelDailyCostOutboxReadBlock          = time.Second
	channelDailyCostOutboxClaimMinIdle       = 30 * time.Second
	channelDailyCostOutboxLeaseDuration      = 30 * time.Second
	channelDailyCostOutboxRecoveryInterval   = 500 * time.Millisecond
	channelDailyCostOutboxMaximumRetryDelay  = 5 * time.Minute
	channelDailyCostOutboxStatsInterval      = 5 * time.Second
	channelDailyCostOutboxCleanupInterval    = time.Hour
	channelDailyCostOutboxProcessedRetention = 30 * 24 * time.Hour
	channelDailyCostOutboxCleanupBatchSize   = 1_000
	channelDailyCostDeadLetterMaxLength      = 10_000
	// Cost payloads are generated by this service and are intentionally kept
	// bounded before they reach Redis or the JSON decoder. A malformed event
	// must be cheap to quarantine rather than becoming an unbounded allocation
	// or a shutdown-time Redis operation.
	channelDailyCostOutboxPayloadMaxLength = 64 * 1024
	channelDailyCostOutboxFailureMaxLength = 512
)

var channelDailyCostDeadLetterScript = redis.NewScript(`
local dead_letter_id = redis.call(
  "XADD", KEYS[1], "MAXLEN", "~", ARGV[1], "*",
  "original_message_id", ARGV[3],
  "event_id", ARGV[4],
  "payload", ARGV[5],
  "error", ARGV[6],
  "failed_at", ARGV[7]
)
redis.call("XACK", KEYS[2], ARGV[2], ARGV[3])
redis.call("XDEL", KEYS[2], ARGV[3])
return dead_letter_id
`)

type channelDailyCostOutboxPayload struct {
	ChannelId             int    `json:"channel_id"`
	OccurredAt            int64  `json:"occurred_at"`
	CostNanoCNY           int64  `json:"cost_nano_cny"`
	ProbeCostNanoCNY      int64  `json:"probe_cost_nano_cny"`
	GroupProbeCostNanoCNY int64  `json:"group_probe_cost_nano_cny"`
	SettledDelta          int64  `json:"settled_delta"`
	UnresolvedDelta       int64  `json:"unresolved_delta"`
	APIKeyId              int    `json:"api_key_id"`
	APIKeyName            string `json:"api_key_name"`
	KeyFingerprint        string `json:"key_fingerprint"`
	KeyDisplay            string `json:"key_display"`
	UserId                int    `json:"user_id"`
	UserAttribution       string `json:"user_attribution"`
	ModelName             string `json:"model_name"`
	SourceKind            string `json:"source_kind"`
}

type ChannelDailyCostOutboxRuntime struct {
	cancel        context.CancelFunc
	done          chan struct{}
	stopOnce      sync.Once
	consumerName  string
	redisClient   *redis.Client
	redisEnabled  bool
	operationWait sync.WaitGroup
}

type ChannelDailyCostReliableStats struct {
	StreamPublished  int64 `json:"stream_published"`
	DBFallbackStored int64 `json:"db_fallback_stored"`
	PublishFailed    int64 `json:"publish_failed"`
	StreamRecovered  int64 `json:"stream_recovered"`
	LedgerApplied    int64 `json:"ledger_applied"`
	LedgerFailed     int64 `json:"ledger_failed"`
	DeadLettered     int64 `json:"dead_lettered"`
	OutboxPending    int64 `json:"outbox_pending"`
	OutboxOldestAt   int64 `json:"outbox_oldest_at"`
	OutboxRetryCount int64 `json:"outbox_retry_count"`
}

var (
	channelDailyCostReliableOutboxActive atomic.Bool
	channelDailyCostReliableStatsState   struct {
		streamPublished  atomic.Int64
		dbFallbackStored atomic.Int64
		publishFailed    atomic.Int64
		streamRecovered  atomic.Int64
		ledgerApplied    atomic.Int64
		ledgerFailed     atomic.Int64
		deadLettered     atomic.Int64
		outboxPending    atomic.Int64
		outboxOldestAt   atomic.Int64
		outboxRetryCount atomic.Int64
	}
)

func channelDailyCostReliableOutboxEnabled() bool {
	return common.GetEnvOrDefaultBool("CHANNEL_DAILY_COST_RELIABLE_OUTBOX", true)
}

func channelDailyCostReliableOutboxIsActive() bool {
	return channelDailyCostReliableOutboxEnabled() && channelDailyCostReliableOutboxActive.Load()
}

func publishChannelDailyCostReliableEvent(ctx context.Context, delta model.ChannelDailyCostDelta) error {
	delta.EventId = strings.TrimSpace(delta.EventId)
	if delta.EventId == "" || len(delta.EventId) > model.ChannelDailyCostOutboxEventIDMaxLength {
		return errors.New("渠道成本可靠事件 ID 无效")
	}
	if err := model.ValidateChannelDailyCostDelta(delta); err != nil {
		return fmt.Errorf("渠道成本可靠事件内容无效: %w", err)
	}
	payload, err := common.Marshal(channelDailyCostOutboxPayloadFromDelta(delta))
	if err != nil {
		return err
	}
	if len(payload) > channelDailyCostOutboxPayloadMaxLength {
		return errors.New("渠道成本可靠事件 payload 过大")
	}

	client := common.RedisMonitorWriteClient()
	if common.RedisEnabled && client != nil {
		publishCtx, cancel := context.WithTimeout(context.WithoutCancel(nonNilContext(ctx)), channelDailyCostOutboxPublishTimeout)
		_, publishErr := client.XAdd(publishCtx, &redis.XAddArgs{
			Stream: ChannelDailyCostRedisStream,
			ID:     "*",
			Values: map[string]interface{}{
				channelDailyCostRedisFieldEventID: delta.EventId,
				channelDailyCostRedisFieldPayload: string(payload),
			},
		}).Result()
		cancel()
		if publishErr == nil {
			channelDailyCostReliableStatsState.streamPublished.Add(1)
			return nil
		}
		logger.LogWarn(ctx, fmt.Sprintf("渠道成本 Stream 写入失败，切换到数据库 outbox: %v", publishErr))
	}

	fallbackCtx, cancel := context.WithTimeout(context.WithoutCancel(nonNilContext(ctx)), channelDailyCostOutboxDBFallbackTimeout)
	inserted, err := model.StoreChannelDailyCostOutboxEventsWithResult(fallbackCtx, []model.ChannelDailyCostDelta{delta})
	cancel()
	if err == nil {
		channelDailyCostReliableStatsState.dbFallbackStored.Add(1)
		channelDailyCostReliableStatsState.outboxPending.Add(inserted)
		return nil
	}
	channelDailyCostReliableStatsState.publishFailed.Add(1)
	logger.LogError(ctx, fmt.Sprintf("渠道成本可靠缓冲不可用，事件 %s 未被接受: %v", delta.EventId, err))
	return err
}

func StartChannelDailyCostOutboxRuntime() (*ChannelDailyCostOutboxRuntime, error) {
	// Startup must establish the runtime state afresh. This matters for tests
	// and controlled restarts that reuse the process package state.
	channelDailyCostReliableOutboxActive.Store(false)
	ctx, cancel := context.WithCancel(context.Background())
	instanceIdentity := channelMonitorRedisKeyPart(channelMonitorRedisInstanceIdentity(), "node")
	if len(instanceIdentity) > 64 {
		instanceIdentity = instanceIdentity[:64]
	}
	runtime := &ChannelDailyCostOutboxRuntime{
		cancel:       cancel,
		done:         make(chan struct{}),
		consumerName: "channel-cost-" + instanceIdentity + "-" + common.GetUUID(),
		redisClient:  common.RedisMonitorConsumerClient(),
	}
	runtime.redisEnabled = common.RedisEnabled && runtime.redisClient != nil
	checkCtx, checkCancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	_, err := model.GetChannelDailyCostOutboxStats(checkCtx)
	checkCancel()
	if err != nil {
		cancel()
		close(runtime.done)
		return nil, fmt.Errorf("渠道成本数据库 outbox 不可用: %w", err)
	}
	// Disabling the producer is an emergency rollback to the legacy batcher,
	// not permission to abandon events already accepted by the reliable path.
	// Keep the drain workers alive while leaving the producer gate inactive.
	if channelDailyCostReliableOutboxEnabled() {
		channelDailyCostReliableOutboxActive.Store(true)
	}
	go runtime.run(ctx)
	return runtime, nil
}

func (runtime *ChannelDailyCostOutboxRuntime) run(ctx context.Context) {
	defer close(runtime.done)
	runtime.operationWait.Add(1)
	go func() {
		defer runtime.operationWait.Done()
		runtime.runDBRecovery(ctx)
	}()
	if runtime.redisEnabled {
		runtime.operationWait.Add(1)
		go func() {
			defer runtime.operationWait.Done()
			runtime.runRedisConsumer(ctx)
		}()
	}
	runtime.operationWait.Wait()
}

func (runtime *ChannelDailyCostOutboxRuntime) Stop(ctx context.Context) error {
	if runtime == nil {
		return nil
	}
	runtime.stopOnce.Do(func() {
		channelDailyCostReliableOutboxActive.Store(false)
		runtime.cancel()
	})
	select {
	case <-runtime.done:
		return nil
	case <-nonNilContext(ctx).Done():
		return nonNilContext(ctx).Err()
	}
}

func (runtime *ChannelDailyCostOutboxRuntime) runRedisConsumer(ctx context.Context) {
	retryDelay := time.Second
	for ctx.Err() == nil {
		if err := runtime.initRedisStream(ctx); err != nil {
			logger.LogWarn(ctx, fmt.Sprintf("渠道成本 Stream 初始化失败，将自动重试: %v", err))
		} else if err := runtime.consumeRedisBatch(ctx); err != nil && ctx.Err() == nil {
			logger.LogWarn(ctx, fmt.Sprintf("渠道成本 Stream 消费失败，将自动重试: %v", err))
		} else {
			retryDelay = time.Second
			continue
		}
		timer := time.NewTimer(retryDelay)
		select {
		case <-ctx.Done():
			if !timer.Stop() {
				<-timer.C
			}
			return
		case <-timer.C:
		}
		retryDelay = min(retryDelay*2, 30*time.Second)
	}
}

func (runtime *ChannelDailyCostOutboxRuntime) initRedisStream(ctx context.Context) error {
	opCtx, cancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	defer cancel()
	err := runtime.redisClient.Do(
		opCtx, "XGROUP", "CREATE", ChannelDailyCostRedisStream,
		ChannelDailyCostRedisConsumerGroup, "0", "MKSTREAM",
	).Err()
	if channelMonitorRedisBusyGroupError(err) {
		return nil
	}
	return err
}

func (runtime *ChannelDailyCostOutboxRuntime) consumeRedisBatch(ctx context.Context) error {
	messages, err := runtime.claimRedisPending(ctx)
	if err != nil {
		return err
	}
	if len(messages) == 0 {
		messages, err = runtime.readOwnedRedisPending(ctx)
		if err != nil {
			return err
		}
	}
	if len(messages) == 0 {
		messages, err = runtime.readNewRedisMessages(ctx)
		if err != nil {
			return err
		}
	}
	if len(messages) == 0 {
		return nil
	}

	deltas := make([]model.ChannelDailyCostDelta, 0, len(messages))
	validMessages := make([]redis.XMessage, 0, len(messages))
	messageIDs := make([]string, 0, len(messages))
	for _, message := range messages {
		delta, parseErr := channelDailyCostDeltaFromRedisMessage(message)
		if parseErr != nil {
			if deadErr := runtime.deadLetterRedisMessage(ctx, message, parseErr); deadErr != nil {
				return deadErr
			}
			continue
		}
		deltas = append(deltas, delta)
		validMessages = append(validMessages, message)
		messageIDs = append(messageIDs, message.ID)
	}
	if len(deltas) == 0 {
		return nil
	}
	opCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), channelDailyCostOutboxDBOperationTimeout)
	inserted, err := model.StoreChannelDailyCostOutboxEventsWithResult(opCtx, deltas)
	cancel()
	if err != nil && !errors.Is(err, model.ErrChannelDailyCostOutboxEventIDCollision) {
		return err
	}
	if errors.Is(err, model.ErrChannelDailyCostOutboxEventIDCollision) {
		inserted = 0
		messageIDs = messageIDs[:0]
		for index, delta := range deltas {
			opCtx, cancel = context.WithTimeout(context.WithoutCancel(ctx), channelDailyCostOutboxDBOperationTimeout)
			stored, storeErr := model.StoreChannelDailyCostOutboxEventsWithResult(opCtx, []model.ChannelDailyCostDelta{delta})
			cancel()
			if errors.Is(storeErr, model.ErrChannelDailyCostOutboxEventIDCollision) {
				if deadErr := runtime.deadLetterRedisMessage(ctx, validMessages[index], storeErr); deadErr != nil {
					return deadErr
				}
				continue
			}
			if storeErr != nil {
				return storeErr
			}
			inserted += stored
			messageIDs = append(messageIDs, validMessages[index].ID)
		}
	}
	channelDailyCostReliableStatsState.outboxPending.Add(inserted)
	if len(messageIDs) == 0 {
		return nil
	}
	ackCtx, ackCancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	defer ackCancel()
	pipe := runtime.redisClient.TxPipeline()
	pipe.XAck(ackCtx, ChannelDailyCostRedisStream, ChannelDailyCostRedisConsumerGroup, messageIDs...)
	pipe.XDel(ackCtx, ChannelDailyCostRedisStream, messageIDs...)
	if _, err = pipe.Exec(ackCtx); err != nil {
		return err
	}
	channelDailyCostReliableStatsState.streamRecovered.Add(int64(len(messageIDs)))
	return nil
}

func (runtime *ChannelDailyCostOutboxRuntime) claimRedisPending(ctx context.Context) ([]redis.XMessage, error) {
	opCtx, cancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	defer cancel()
	result, err := runtime.redisClient.Do(
		opCtx, "XAUTOCLAIM", ChannelDailyCostRedisStream, ChannelDailyCostRedisConsumerGroup,
		runtime.consumerName, channelDailyCostOutboxClaimMinIdle.Milliseconds(), "0-0", "COUNT", channelDailyCostOutboxBatchSize,
	).Result()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return parseChannelMonitorRedisAutoClaimMessages(result)
}

func (runtime *ChannelDailyCostOutboxRuntime) readOwnedRedisPending(ctx context.Context) ([]redis.XMessage, error) {
	return runtime.readRedisGroup(ctx, "0", -1)
}

func (runtime *ChannelDailyCostOutboxRuntime) readNewRedisMessages(ctx context.Context) ([]redis.XMessage, error) {
	return runtime.readRedisGroup(ctx, ">", channelDailyCostOutboxReadBlock)
}

func (runtime *ChannelDailyCostOutboxRuntime) readRedisGroup(ctx context.Context, id string, block time.Duration) ([]redis.XMessage, error) {
	streams, err := runtime.redisClient.XReadGroup(ctx, &redis.XReadGroupArgs{
		Group: ChannelDailyCostRedisConsumerGroup, Consumer: runtime.consumerName,
		Streams: []string{ChannelDailyCostRedisStream, id}, Count: channelDailyCostOutboxBatchSize, Block: block,
	}).Result()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var messages []redis.XMessage
	for _, stream := range streams {
		messages = append(messages, stream.Messages...)
	}
	return messages, nil
}

func (runtime *ChannelDailyCostOutboxRuntime) deadLetterRedisMessage(ctx context.Context, message redis.XMessage, cause error) error {
	payload, _ := redisStringValue(message.Values[channelDailyCostRedisFieldPayload])
	eventID, _ := redisStringValue(message.Values[channelDailyCostRedisFieldEventID])
	causeMessage := "unknown error"
	if cause != nil {
		causeMessage = cause.Error()
	}
	// A malformed Stream entry is not trusted to obey the producer's event ID
	// bound. Keep dead-letter forensics bounded even when a producer injected a
	// very large event_id value before the consumer could validate it.
	if len(eventID) > model.ChannelDailyCostOutboxEventIDMaxLength {
		eventID = eventID[:model.ChannelDailyCostOutboxEventIDMaxLength]
	}
	if len(payload) > channelDailyCostOutboxPayloadMaxLength {
		payload = payload[:channelDailyCostOutboxPayloadMaxLength]
	}
	if len(causeMessage) > channelDailyCostOutboxFailureMaxLength {
		causeMessage = causeMessage[:channelDailyCostOutboxFailureMaxLength]
	}
	opCtx, cancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	defer cancel()
	if _, err := channelDailyCostDeadLetterScript.Run(
		opCtx,
		runtime.redisClient,
		[]string{ChannelDailyCostRedisDeadLetter, ChannelDailyCostRedisStream},
		channelDailyCostDeadLetterMaxLength,
		ChannelDailyCostRedisConsumerGroup,
		message.ID,
		eventID,
		payload,
		causeMessage,
		time.Now().Unix(),
	).Result(); err != nil {
		return err
	}
	channelDailyCostReliableStatsState.deadLettered.Add(1)
	logger.LogError(ctx, fmt.Sprintf("渠道成本事件 %s 无法解析，已进入死信队列: %v", eventID, cause))
	return nil
}

func (runtime *ChannelDailyCostOutboxRuntime) runDBRecovery(ctx context.Context) {
	ticker := time.NewTicker(channelDailyCostOutboxRecoveryInterval)
	defer ticker.Stop()
	nextStatsRefresh := time.Time{}
	nextCleanup := time.Time{}
	for {
		if err := recoverChannelDailyCostOutboxBatch(ctx, runtime.consumerName); err != nil && ctx.Err() == nil {
			logger.LogWarn(ctx, fmt.Sprintf("渠道成本 outbox 恢复失败，将自动重试: %v", err))
		}
		now := time.Now()
		if !now.Before(nextStatsRefresh) {
			refreshChannelDailyCostOutboxStats(ctx)
			nextStatsRefresh = now.Add(channelDailyCostOutboxStatsInterval)
		}
		if !now.Before(nextCleanup) {
			cleanupCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), channelDailyCostOutboxDBOperationTimeout)
			deleted, err := model.DeleteProcessedChannelDailyCostOutboxEvents(
				cleanupCtx,
				now.Add(-channelDailyCostOutboxProcessedRetention).Unix(),
				channelDailyCostOutboxCleanupBatchSize,
			)
			cancel()
			if err != nil && ctx.Err() == nil {
				logger.LogWarn(ctx, fmt.Sprintf("渠道成本 outbox 历史清理失败，将自动重试: %v", err))
			}
			if deleted == channelDailyCostOutboxCleanupBatchSize {
				nextCleanup = now.Add(channelDailyCostOutboxRecoveryInterval)
			} else {
				nextCleanup = now.Add(channelDailyCostOutboxCleanupInterval)
			}
		}
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}
	}
}

func recoverChannelDailyCostOutboxBatch(ctx context.Context, owner string) error {
	now := time.Now().Unix()
	return recoverChannelDailyCostOutboxBatchReadyBefore(ctx, owner, now, now)
}

func recoverChannelDailyCostOutboxBatchReadyBefore(ctx context.Context, owner string, now int64, readyBefore int64) error {
	opCtx, cancel := context.WithTimeout(ctx, channelDailyCostOutboxDBOperationTimeout)
	claimed, err := model.ClaimChannelDailyCostOutboxEvents(opCtx, owner, now, readyBefore, channelDailyCostOutboxLeaseDuration, channelDailyCostOutboxBatchSize)
	cancel()
	if err != nil || len(claimed) == 0 {
		return err
	}
	ids := make([]int64, 0, len(claimed))
	maxAttempt := int64(1)
	for _, event := range claimed {
		ids = append(ids, event.Id)
		maxAttempt = max(maxAttempt, event.AttemptCount)
	}
	applyCtx, applyCancel := context.WithTimeout(context.WithoutCancel(ctx), channelDailyCostOutboxDBOperationTimeout)
	appliedCount, err := model.ApplyClaimedChannelDailyCostOutboxEventsWithResult(applyCtx, owner, ids, time.Now().Unix())
	applyCancel()
	if err == nil {
		channelDailyCostReliableStatsState.ledgerApplied.Add(appliedCount)
		decrementChannelDailyCostOutboxPending(appliedCount)
		return nil
	}
	failedIDs := ids
	if errors.Is(err, model.ErrChannelDailyCostLedgerOverflow) && len(claimed) > 1 {
		failedIDs = make([]int64, 0, len(claimed))
		appliedCount := int64(0)
		for index, event := range claimed {
			applyCtx, applyCancel = context.WithTimeout(context.WithoutCancel(ctx), channelDailyCostOutboxDBOperationTimeout)
			applied, applyErr := model.ApplyClaimedChannelDailyCostOutboxEventsWithResult(applyCtx, owner, []int64{event.Id}, time.Now().Unix())
			applyCancel()
			if applyErr == nil {
				appliedCount += applied
				continue
			}
			err = applyErr
			failedIDs = append(failedIDs, event.Id)
			if errors.Is(applyErr, model.ErrChannelDailyCostLedgerOverflow) {
				continue
			}
			for _, remaining := range claimed[index+1:] {
				failedIDs = append(failedIDs, remaining.Id)
			}
			break
		}
		if appliedCount > 0 {
			channelDailyCostReliableStatsState.ledgerApplied.Add(appliedCount)
			decrementChannelDailyCostOutboxPending(appliedCount)
		}
		if len(failedIDs) == 0 {
			return nil
		}
		maxAttempt = 1
		failed := make(map[int64]struct{}, len(failedIDs))
		for _, id := range failedIDs {
			failed[id] = struct{}{}
		}
		for _, event := range claimed {
			if _, exists := failed[event.Id]; exists {
				maxAttempt = max(maxAttempt, event.AttemptCount)
			}
		}
	}
	retryDelay := time.Second * time.Duration(1<<min(maxAttempt-1, int64(8)))
	retryDelay = min(retryDelay, channelDailyCostOutboxMaximumRetryDelay)
	failCtx, failCancel := context.WithTimeout(context.Background(), channelDailyCostOutboxDBOperationTimeout)
	released, failErr := model.FailClaimedChannelDailyCostOutboxEventsWithResult(failCtx, owner, failedIDs, time.Now().Add(retryDelay).Unix(), err)
	failCancel()
	if failErr != nil {
		channelDailyCostReliableStatsState.ledgerFailed.Add(int64(len(failedIDs)))
		return fmt.Errorf("应用 outbox 失败: %v；释放租约失败: %w", err, failErr)
	}
	if released == 0 {
		// Another worker finalized or took over every failed row while this
		// worker was applying. Do not report a false failure or retry it.
		return nil
	}
	channelDailyCostReliableStatsState.ledgerFailed.Add(released)
	return err
}

func FlushChannelDailyCostOutbox(ctx context.Context) error {
	owner := "channel-cost-flush-" + common.GetUUID()
	for {
		stats, err := model.GetChannelDailyCostOutboxStats(nonNilContext(ctx))
		if err != nil || stats.PendingCount == 0 {
			return err
		}
		before := stats.PendingCount
		now := time.Now()
		if err := recoverChannelDailyCostOutboxBatchReadyBefore(
			nonNilContext(ctx), owner, now.Unix(), math.MaxInt64,
		); err != nil {
			return err
		}
		after, err := model.GetChannelDailyCostOutboxStats(nonNilContext(ctx))
		if err != nil {
			return err
		}
		if after.PendingCount >= before {
			return errors.New("渠道成本 outbox flush 未取得进展")
		}
	}
}

func GetChannelDailyCostReliableStats() ChannelDailyCostReliableStats {
	return ChannelDailyCostReliableStats{
		StreamPublished:  channelDailyCostReliableStatsState.streamPublished.Load(),
		DBFallbackStored: channelDailyCostReliableStatsState.dbFallbackStored.Load(),
		PublishFailed:    channelDailyCostReliableStatsState.publishFailed.Load(),
		StreamRecovered:  channelDailyCostReliableStatsState.streamRecovered.Load(),
		LedgerApplied:    channelDailyCostReliableStatsState.ledgerApplied.Load(),
		LedgerFailed:     channelDailyCostReliableStatsState.ledgerFailed.Load(),
		DeadLettered:     channelDailyCostReliableStatsState.deadLettered.Load(),
		OutboxPending:    max(0, channelDailyCostReliableStatsState.outboxPending.Load()),
		OutboxOldestAt:   channelDailyCostReliableStatsState.outboxOldestAt.Load(),
		OutboxRetryCount: channelDailyCostReliableStatsState.outboxRetryCount.Load(),
	}
}

func refreshChannelDailyCostOutboxStats(ctx context.Context) {
	queryCtx, cancel := context.WithTimeout(context.WithoutCancel(nonNilContext(ctx)), channelDailyCostOutboxDBOperationTimeout)
	stats, err := model.GetChannelDailyCostOutboxStats(queryCtx)
	cancel()
	if err != nil {
		return
	}
	channelDailyCostReliableStatsState.outboxPending.Store(stats.PendingCount)
	channelDailyCostReliableStatsState.outboxOldestAt.Store(stats.OldestPending)
	channelDailyCostReliableStatsState.outboxRetryCount.Store(stats.RetryCount)
}

func channelDailyCostReliablePendingCount() int64 {
	return max(0, channelDailyCostReliableStatsState.outboxPending.Load())
}

func decrementChannelDailyCostOutboxPending(delta int64) {
	if delta <= 0 {
		return
	}
	for {
		current := channelDailyCostReliableStatsState.outboxPending.Load()
		next := int64(0)
		if current > 0 && delta < current {
			next = current - delta
		}
		if channelDailyCostReliableStatsState.outboxPending.CompareAndSwap(current, next) {
			return
		}
	}
}

func channelDailyCostOutboxPayloadFromDelta(delta model.ChannelDailyCostDelta) channelDailyCostOutboxPayload {
	return channelDailyCostOutboxPayload{
		ChannelId: delta.ChannelId, OccurredAt: delta.OccurredAt, CostNanoCNY: delta.CostNanoCNY,
		ProbeCostNanoCNY: delta.ProbeCostNanoCNY, GroupProbeCostNanoCNY: delta.GroupProbeCostNanoCNY,
		SettledDelta: delta.SettledDelta, UnresolvedDelta: delta.UnresolvedDelta,
		APIKeyId: delta.APIKeyId, APIKeyName: delta.APIKeyName,
		KeyFingerprint: delta.KeyFingerprint, KeyDisplay: delta.KeyDisplay, UserId: delta.UserId,
		UserAttribution: delta.UserAttribution, ModelName: delta.ModelName, SourceKind: delta.SourceKind,
	}
}

func (payload channelDailyCostOutboxPayload) delta(eventID string) model.ChannelDailyCostDelta {
	return model.ChannelDailyCostDelta{
		EventId: eventID, ChannelId: payload.ChannelId, OccurredAt: payload.OccurredAt,
		CostNanoCNY: payload.CostNanoCNY, ProbeCostNanoCNY: payload.ProbeCostNanoCNY,
		GroupProbeCostNanoCNY: payload.GroupProbeCostNanoCNY, SettledDelta: payload.SettledDelta,
		UnresolvedDelta: payload.UnresolvedDelta, APIKeyId: payload.APIKeyId, APIKeyName: payload.APIKeyName,
		KeyFingerprint: payload.KeyFingerprint, KeyDisplay: payload.KeyDisplay, UserId: payload.UserId,
		UserAttribution: payload.UserAttribution, ModelName: payload.ModelName, SourceKind: payload.SourceKind,
	}
}

func channelDailyCostDeltaFromRedisMessage(message redis.XMessage) (model.ChannelDailyCostDelta, error) {
	eventID, ok := redisStringValue(message.Values[channelDailyCostRedisFieldEventID])
	eventID = strings.TrimSpace(eventID)
	if !ok || eventID == "" {
		return model.ChannelDailyCostDelta{}, errors.New("cost Stream event_id 缺失")
	}
	if len(eventID) > model.ChannelDailyCostOutboxEventIDMaxLength {
		return model.ChannelDailyCostDelta{}, errors.New("cost Stream event_id 过长")
	}
	payloadJSON, ok := redisStringValue(message.Values[channelDailyCostRedisFieldPayload])
	if !ok || payloadJSON == "" {
		return model.ChannelDailyCostDelta{}, errors.New("cost Stream payload 缺失")
	}
	if len(payloadJSON) > channelDailyCostOutboxPayloadMaxLength {
		return model.ChannelDailyCostDelta{}, errors.New("cost Stream payload 过大")
	}
	var payload channelDailyCostOutboxPayload
	if err := common.Unmarshal([]byte(payloadJSON), &payload); err != nil {
		return model.ChannelDailyCostDelta{}, err
	}
	delta := payload.delta(eventID)
	if err := model.ValidateChannelDailyCostDelta(delta); err != nil {
		return model.ChannelDailyCostDelta{}, err
	}
	return delta, nil
}

func redisStringValue(value interface{}) (string, bool) {
	switch typed := value.(type) {
	case string:
		return typed, true
	case []byte:
		return string(typed), true
	default:
		return "", false
	}
}

func nonNilContext(ctx context.Context) context.Context {
	if ctx == nil {
		return context.Background()
	}
	return ctx
}
